### ISSUE TITLE
生存率を上げる機能について

### ISSUE THREAD

**Issue by Ryokugyoku** [tech-creative-club/disaster-posts#22]
主に生存率を上げるための機能が必要になりそう。
パッと思いつくものだと下記のような機能が挙げられる
・応急処置の方法
・各種用途別の代替品になるような一覧
・道路などの危険情報の収集
　＞収集方法は、ユーザが投稿している写真と写真の位置情報をもとに判別する、　これに関しては写真と地図を紐付けて個人でその写真を見て判断する形にする　※発展系としては、投稿された画像をもとにフェイクかどうかレベルを設ける

その他
大きな災害の場合極限状態に陥ることを考慮してレイアウトは複雑にするのではなく、簡素にしてパニック状態でも操作しやすいように設計？
アプリのカラーは精神的に鎮静作用の高い配色にする？　※専門家に聞くほうがいいかもしれない

**Comment by Ryokugyoku** [comment]
確かにそうですね。不適切でした。削除をお願いしても良いでしょうか？

**Comment by tecsoc** [comment]
ありがとうございます。でもご意見ありがとうございます
