### ISSUE TITLE
コントリビュートガイド？READMEの作成

### ISSUE THREAD

**Issue by tecsoc** [tech-creative-club/disaster-posts#6]
参考：
docsディレクトリ配下が個人的には良いかな

https://docs.github.com/ja/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

- 基本的にタスクはIssueベースで行う
- Issueにアサインして開発していただく
- 優先度は[Projects](https://github.com/tech-creative-club/disaster-posts/projects)を参照
- 議論したい内容が発生したらGitHubの[Discussions](https://github.com/tech-creative-club/disaster-posts/discussions)に投稿

**Comment by Kokohachi** [comment]
docs/配下で作成を開始しました。

**Comment by tecsoc** [comment]
@Kokohachi 
ある程度できたらmainブランチ向きでPull Requestお願いします！

**Comment by tecsoc** [comment]
#14 にて大枠を作成いただいたので一旦Close
